export { default as AppMain } from './AppMain.vue'
export { default as Navbar } from './Navbar/Index.vue'
export { default as Settings } from './Settings/Index.vue'
export { default as Sidebar } from './Sidebar/Index.vue'
export { default as TagsView } from './TagsView/Index.vue'
